name: Github_action

on:  
  push:
    branches: [main]
  pull_request:  
    branches: [main]   
    
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: docker/build-push-action@v5
      - name: Docker image
        run:  docker build -t ${{ inputs.image }} -f ${{ inputs.dockerfile }} --target ${{ inputs.target }} ${{ inputs.context }}
