name: Github_action

on:  
  push:
    branches: [main]
  pull_request:  
    branches: [main]   
    
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: docker/build-push-action@v5
      - name: Docker image
        run: docker build --file ./Module_4/Dockerfile --tag my-image-name:$(date +%s)
