name: Github_action

on:  
  push:
    branches: [main]
  pull_request:  
    branches: [main]   
    
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - uses: docker/build-push-action@v5
      - name: Docker image
        with:
          context: .
          file: ./app/Dockerfile
          push: true
          tags: myimage:latest
          outputs: type=docker,dest=/tmp/myimage.tar 
